prueba/config/routes.rb
Rails.application.routes.draw do
  resources :proveedors
  resources :bancos
  devise_for :users
  root to: "bancos#index" 
end

prueba/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

prueba/app/models/banco.rb
class Banco < ApplicationRecord
  validates :nombre, presence: true, length: {maximum: 50}
end

prueba/app/models/proveedor.rb
class Proveedor < ApplicationRecord
  belongs_to :banco
  validates :nit, format: { with: /\A\d{9}-?\d?\z/, message: "El formato del NIT no es válido" }
  validates :celular, length: {maximum: 10}
  validates :numero_cuenta, length: {maximum: 15  }
  validates :nombre, presence: true
  validates :contacto, presence: true
end

prueba/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

prueba/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

prueba/app/controllers/bancos_controller.rb
class BancosController < ApplicationController
  before_action :set_banco, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /bancos or /bancos.json
  def index
    @bancos = Banco.all
  end

  # GET /bancos/1 or /bancos/1.json
  def show
  end

  # GET /bancos/new
  def new
    @banco = Banco.new
  end

  # GET /bancos/1/edit
  def edit
  end

  # POST /bancos or /bancos.json
  def create
    @banco = Banco.new(banco_params)

    respond_to do |format|
      if @banco.save
        format.html { redirect_to banco_url(@banco), notice: "Banco was successfully created." }
        format.json { render :show, status: :created, location: @banco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bancos/1 or /bancos/1.json
  def update
    respond_to do |format|
      if @banco.update(banco_params)
        format.html { redirect_to banco_url(@banco), notice: "Banco was successfully updated." }
        format.json { render :show, status: :ok, location: @banco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bancos/1 or /bancos/1.json
  def destroy
    @banco.destroy

    respond_to do |format|
      format.html { redirect_to bancos_url, notice: "Banco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banco
      @banco = Banco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def banco_params
      params.require(:banco).permit(:nombre)
    end
end

prueba/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index;end
end

prueba/app/controllers/proveedors_controller.rb
class ProveedorsController < ApplicationController
  before_action :set_proveedor, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /proveedors or /proveedors.json
  def index
    @proveedors = Proveedor.all
  end

  # GET /proveedors/1 or /proveedors/1.json
  def show
  end

  # GET /proveedors/new
  def new
    @proveedor = Proveedor.new
  end

  # GET /proveedors/1/edit
  def edit
  end

  # POST /proveedors or /proveedors.json
  def create
    @proveedor = Proveedor.new(proveedor_params)

    respond_to do |format|
      if @proveedor.save
        format.html { redirect_to proveedor_url(@proveedor), notice: "Proveedor was successfully created." }
        format.json { render :show, status: :created, location: @proveedor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveedors/1 or /proveedors/1.json
  def update
    respond_to do |format|
      if @proveedor.update(proveedor_params)
        format.html { redirect_to proveedor_url(@proveedor), notice: "Proveedor was successfully updated." }
        format.json { render :show, status: :ok, location: @proveedor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedors/1 or /proveedors/1.json
  def destroy
    @proveedor.destroy

    respond_to do |format|
      format.html { redirect_to proveedors_url, notice: "Proveedor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedor
      @proveedor = Proveedor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proveedor_params
      params.require(:proveedor).permit(:nombre, :nit, :contacto, :celular, :banco_id, :numero_cuenta)
    end
end

prueba/app/helpers/application_helper.rb
module ApplicationHelper
end

prueba/app/helpers/bancos_helper.rb
module BancosHelper
end

prueba/app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

prueba/app/views/bancos/_banco.html.erb
<tr>
  <td class="px-6 py-4 whitespace-nowrap text-center">
    <%= banco.nombre %>
  </td>

prueba/app/views/bancos/_form.html.erb
<%= form_with(model: banco, class: "max-w-lg mx-auto") do |form| %>
  <% if banco.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <h2 class="font-bold text-lg mb-2"><%= pluralize(banco.errors.count, "error") %> prohibited this banco from being saved:</h2>

      <ul class="list-disc ml-4">
        <% banco.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-4">
    <%= form.label :nombre, class: "block font-bold mb-2" %>
    <%= form.text_field :nombre, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mt-4">
    <%= form.submit "Guardar", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

prueba/app/views/bancos/edit.html.erb
<div class="flex flex-col items-center justify-center">
  <h1 class="text-2xl font-bold mb-4">Editar banco</h1>

  <%= render "form", banco: @banco %>

  <div class="mt-4">
    <%= link_to "Volver a bancos", bancos_path, class: "bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center focus:outline-none focus:shadow-outline" %>
  </div>
</div>

prueba/app/views/bancos/index.html.erb
<div class="flex flex-col items-center justify-center">
  <p class="text-green-500"><%= notice %></p>

  <h1 class="text-2xl font-bold mb-4"><%= t(:banks) %></h1>
  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
    <%= link_to "Crear banco", new_banco_path %>
  </button> 
  <div id="bancos" class="w-full max-w-lg">
    <div class="border border-gray-200 shadow-md rounded-lg overflow-hidden">
      <table class="min-w-full divide-y divide-gray-200">
        <thead>
          <tr>
            <th><%= t('table_bank.name') %></th>
            <th><%= t('table_bank.option') %></th>
          </tr>
        </thead>
        <tbody>
          <% @bancos.each do |banco| %>
            <%= render banco %>
            <td class="px-6 py-4 whitespace-nowrap">
              <%= link_to "Ver banco", banco, class: "text-blue-500 hover:underline" %>
            </td>
          </tr>
            
          <% end %>
        </tbody>
      </table>
  </div>

  
</div>

prueba/app/views/bancos/new.html.erb
<div class="flex flex-col items-center justify-center">
  <h1 class="text-2xl font-bold mb-4">Nuevo banco</h1>

  <%= render "form", banco: @banco %>

  <div class="mt-4">
    <%= link_to "Volver a bancos", bancos_path, class: "bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center focus:outline-none focus:shadow-outline" %>
  </div>
</div>

prueba/app/views/bancos/show.html.erb
<div class="p-4 bg-white rounded-md shadow-md">
  <p class="text-green-600"><%= notice %></p>
  <div id="bancos" class="w-full max-w-lg">
    <div class="border border-gray-200 shadow-md rounded-lg overflow-hidden">
      <table class="min-w-full divide-y divide-gray-200">
        <thead>
          <tr>
            <th><%= t('table_bank.name') %></th>
            <th><%= t('table_bank.option') %></th>
          </tr>
        </thead>
        <tbody>
            <%= render @banco %>
            <td class="px-6 py-4 whitespace-nowrap">
            <%= link_to "Editar", edit_banco_path(@banco), class: "text-blue-500 hover:underline" %> | <%= button_to "Eliminar", @banco, method: :delete, class: "text-blue-500 hover:underline" %>
            </td>
          </tr>
        </tbody>
     </table>
    </div>
  </div>
</div>

  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
    <%= link_to "Volver a bancos", bancos_path %>
  </button>

prueba/app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba Andres Benavides</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <% if user_signed_in? %> 
      <div> Welcome <%= current_user.email %> </div> 
        <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
      <% else %>
        <%= button_to "Sign in", new_user_session_path %> 
    <% end %>
  </body>
</html>

prueba/app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
   <%= stylesheet_link_tag 'application', media: 'all' %>
  <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <ul class="flex">
      <li class="mr-6">
        <a class="text-blue-500 hover:text-blue-800" href="<%= bancos_path %>">Bancos</a>
      </li>
      <li class="mr-6">
        <a class="text-blue-500 hover:text-blue-800" href="<%= proveedors_path %>">Proveedores</a>
      </li>
      <li class="mr-6">
        <% if user_signed_in? %> 
        <span> Usuario: <%= current_user.email %> </span> 
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "text-blue-500 hover:underline" %> 
        <% else %>
          <%= button_to "Sign in", new_user_session_path, class: "text-blue-500 hover:underline" %> 
        <% end %>
      </li>

      
    </ul>
    <!-- this is where content will be rendered -->
    <%= yield %>
  </body>
</html>

prueba/app/views/proveedors/_form.html.erb
<div class="bg-white px-4 py-6 max-w-md mb-4">
  <%= form_with(model: proveedor) do |form| %>
    <% if proveedor.errors.any? %>
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
        <h2><%= pluralize(proveedor.errors.count, "error") %> prohibited this proveedor from being saved:</h2>

        <ul>
          <% proveedor.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="bg-white px-4 py-6">
      <div class="grid grid-cols-2 gap-4">
        <div>
          <%= form.label :nombre %>
          <%= form.text_field :nombre, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div>
          <%= form.label :nit %>
          <%= form.text_field :nit, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div>
          <%= form.label :contacto %>
          <%= form.text_field :contacto, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div>
          <%= form.label :celular %>
          <%= form.text_field :celular, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div>
          <%= form.label :banco_id %>
          <%= form.select :banco_id, options_for_select(Banco.all.map { |b| [b.nombre, b.id] }), {}, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div>
          <%= form.label :numero_cuenta %>
          <%= form.text_field :numero_cuenta, class: "shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>
      </div>

      <div class="mt-8">
        <%= form.submit "Guardar", class: "py-2 px-4 bg-blue-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2" %>

    </div>
  <% end %>
</div>

prueba/app/views/proveedors/_proveedor.html.erb
<tr>
  <td class="px-6 py-4 whitespace-nowrap text-center">
    <%= proveedor.nombre %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-center">
    <%= proveedor.nit %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-center">
    <%= proveedor.contacto %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-center">
    <%= proveedor.celular %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-center">
    <%= proveedor.banco.nombre %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-center">
    <%= proveedor.numero_cuenta %>
  </td>

prueba/app/views/proveedors/edit.html.erb
<div class="flex flex-col items-center justify-center">
  <h1 class="text-2xl font-bold mb-4">Editar proveedor</h1>

  <%= render "form", proveedor: @proveedor %>

  <div class="mt-4">
    <%= link_to "Volver a proveedores", proveedors_path, class: "bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center focus:outline-none focus:shadow-outline" %>
  </div>
</div>

prueba/app/views/proveedors/index.html.erb
<div class="flex flex-col items-center justify-center">
  <p style="color: green"><%= notice %></p>

  <h1 class="text-2xl font-bold mb-4">Proveedores</h1>

  <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
    <%= link_to "Crear proveedor", new_proveedor_path %>
  </button>
  <div id="proveedors">
    <div class="border border-gray-200 shadow-md rounded-lg overflow-hidden">
      <table class="min-w-full divide-y divide-gray-200">
        <thead>
          <tr>
            <th><%= t('table_provedor.name') %></th>
            <th><%= t('table_provedor.nit') %></th>
            <th><%= t('table_provedor.contact') %></th>
            <th><%= t('table_provedor.phone') %></th>
            <th><%= t(:bank) %></th>
            <th><%= t('table_provedor.count') %></th>
            <th><%= t('table_provedor.option') %></th>
          </tr>
        </thead>
        <tbody>
          <% @proveedors.each do |proveedor| %>
            <%= render proveedor %>
            <td class="px-6 py-4 whitespace-nowrap">
              <%= link_to "Ver proveedor", proveedor, class: "text-blue-500 hover:underline" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

prueba/app/views/proveedors/new.html.erb
<div class="flex flex-col items-center justify-center">
  <h1 class="text-2xl font-bold mb-4">Crear proveedor</h1>

  <%= render "form", proveedor: @proveedor %>

  <div class="mt-4">
    <%= link_to "Volver a proveedores", proveedors_path, class: "bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center focus:outline-none focus:shadow-outline" %>
  </div>
</div>

prueba/app/views/proveedors/show.html.erb
<p style="color: green"><%= notice %></p>

 <div class="border border-gray-200 shadow-md rounded-lg overflow-hidden">
    <table class="min-w-full divide-y divide-gray-200">
      <thead>
        <tr>
          <th><%= t('table_provedor.name') %></th>
          <th><%= t('table_provedor.nit') %></th>
          <th><%= t('table_provedor.contact') %></th>
          <th><%= t('table_provedor.phone') %></th>
          <th><%= t(:bank) %></th>
          <th><%= t('table_provedor.count') %></th>
          <th><%= t('table_provedor.option') %></th>
        </tr>
      </thead>
      <tbody>
        <%= render @proveedor %>
          <td class="px-6 py-4 whitespace-nowrap">
          <%= link_to "Editar", edit_proveedor_path(@proveedor), class: "text-blue-500 hover:underline" %> | <%= button_to "Eliminar", @proveedor, method: :delete, class: "text-blue-500 hover:underline" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
  <%= link_to "Volver a proveedores", proveedors_path %>
</button>